
docker build -t test .

INPUT_POSTGRES_USER=postgres
INPUT_POSTGRES_DB=postgres
INPUT_POSTGRES_PASSWORD=postgres
INPUT_POSTGRES_EXTENSIONS="uuid-ossp ltree"
INPUT_APP_USER=app
INPUT_APP_USER_PASSWORD=app
INPUT_APP_DB="app app1 app2"
INPUT_EXPOSED_POSTGRES_PORT=5432
INPUT_POSTGRES_IMAGE_TAG=latest


docker run \
 -e INPUT_POSTGRES_USER="${INPUT_POSTGRES_USER}" \
 -e INPUT_POSTGRES_DB="${INPUT_POSTGRES_DB}" \
 -e INPUT_POSTGRES_PASSWORD"=${INPUT_POSTGRES_PASSWORD}" \
 -e INPUT_POSTGRES_EXTENSIONS"=${INPUT_POSTGRES_EXTENSIONS}" \
 -e INPUT_APP_USER"=${INPUT_APP_USER}" \
 -e INPUT_APP_USER_PASSWORD"=${INPUT_APP_USER_PASSWORD}" \
 -e INPUT_APP_DB="$INPUT_APP_DB" \
 -e INPUT_EXPOSED_POSTGRES_PORT"=${INPUT_EXPOSED_POSTGRES_PORT}" \
 -e INPUT_POSTGRES_IMAGE_TAG"=${INPUT_POSTGRES_IMAGE_TAG}" \
 -v /var/run/docker.sock:/var/run/docker.sock \
 test
