name: Test postgresql-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: 12-alpine
          app_user: app
          app_user_password: develop
          app_db: app app2 app3 app4
      - name: Test Connection to database
        working-directory: test
        run: php test.php

